name: vscanner_finalproject_csci4100
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  sqflite:
  http: 
  latlong:
  geolocator: ^7.7.1
  geocoding:
  flutter_map:
  flutter_local_notifications:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter:
  flutter_barcode_scanner: ^2.0.0
  flutter_native_splash: ^0.2.8
  


  flutter_lints: ^1.0.0

flutter_native_splash:
  color: '#4caf50'
  image: images/smaller_splash.png
  android: true
  ios: true

flutter:
  assets:
    - images/mapimage.jpg
    - images/vscanner_splash_screen.png
    - images/vegescannerlong.png
    - images/vegescanner_splash.png
    - images/smaller_splash.png
    - images/vegan_icon_false.png
    - images/vegan_icon_maybe.png
    - images/vegan_icon_true.png
    - images/vegetarian_icon_false.png
    - images/vegetarian_icon_maybe.png
    - images/vegetarian_icon_true.png
    - images/barcode_not_found.png
    - images/error_barcode.png
    - images/no_image.jpg
    - images/vegescanner_homescreen_splash.png
    - images/openfoodfacts.png
    - images/duplicatebarcode.png
  uses-material-design: true

